### ISSUE TITLE
PHP 8 support status

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#7050]
## Craft CMS

- [x] oAuth2 Client currently isn't installable on PHP 8 via Composer: https://github.com/thephpleague/oauth2-client/issues/862

- [x] Minify currently isn't installable on PHP 8 via Composer: https://github.com/mrclay/minify/issues/681

- [x] Guzzle added support for PHP 8 in 7.2.0.  Craft 3 currently uses ^6.5.1. 7.0.0 has a couple breaking changes but we don’t anticipate they will affect plugins (only one of them affects Craft and is [easy to work around](https://github.com/craftcms/cms/commit/802444d08c888dd217f3abfa57a7897dbc175506), but it requires PHP 7.2+ so we would need to change our Guzzle requirement to `^6.5.1 || ^7.2.0`, to maintain PHP 7.0 support.

- [x] Composer added support for PHP 8 in Composer 2. Craft uses Composer 1.1.10 internally. Will need to update it to Composer 2 when it is officially released and test for breaking changes. https://github.com/composer/composer/milestone/23

- [x] Imagine 1.2.4 fixed PHP 8 compatibility

- [x] Yii 2 has some outstanding issues which look to be fixed for their next release: https://github.com/yiisoft/yii2/pull/18317

- [x] The feed reader we're currently using has some outstanding issues, although initial tests show they don't affect Craft: https://github.com/laminas/laminas-feed/issues/27

- [x] https://github.com/yiisoft/yii2/pull/18407 needs to get released to fix #7174

- [x] SVG Sanitizer is broken on PHP 8. Have submitted a PR: https://github.com/darylldoyle/svg-sanitizer/issues/46

### Mailgun

- [ ] [cspoo/swiftmailer-mailgun-bundle](https://github.com/tehplague/swiftmailer-mailgun-bundle) isn’t compatible with php-http/guzzle7-adapter, due to a [php-http/httplug conflict](https://github.com/tehplague/swiftmailer-mailgun-bundle/issues/79). Once that is resolved, we can release a new version of Mailgun that requires Craft 3.6+ and guzzle7-adapter.

### Commerce

- [ ] dompdf has some outstanding issues https://github.com/dompdf/dompdf/issues/2242 and currently isn't installable https://github.com/dompdf/dompdf/blob/master/composer.json#L35

**Comment by brandonkelly** [comment]
Related: #6997

**Comment by faradaytrs** [comment]
as i understand yiisoft/yii2#18407 has been released and fixed #7174
Any plans on 3.6 official release?

**Comment by brandonkelly** [comment]
Craft 3.6.0 is out now with PHP 8 support!

**Comment by OwenMelbz** [comment]
What's the chances we can re-pin this :D 

Mainly due to the official mailgun package is still incompatible :(

**Comment by davidhellmann** [comment]
Looks like the mailgun plugjn is updated?

**Comment by qrazi** [comment]
Look like it indeed: https://github.com/craftcms/mailgun/blob/main/CHANGELOG.md#200---2021-11-06

**Comment by brandonkelly** [comment]
Yep! Thanks for the reminder to update this.
